// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cart/proto/cart.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CartInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId            int64    `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SizeId               int64    `protobuf:"varint,4,opt,name=size_id,json=sizeId,proto3" json:"size_id,omitempty"`
	Num                  int64    `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartInfo) Reset()         { *m = CartInfo{} }
func (m *CartInfo) String() string { return proto.CompactTextString(m) }
func (*CartInfo) ProtoMessage()    {}
func (*CartInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{0}
}

func (m *CartInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartInfo.Unmarshal(m, b)
}
func (m *CartInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartInfo.Marshal(b, m, deterministic)
}
func (m *CartInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartInfo.Merge(m, src)
}
func (m *CartInfo) XXX_Size() int {
	return xxx_messageInfo_CartInfo.Size(m)
}
func (m *CartInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CartInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CartInfo proto.InternalMessageInfo

func (m *CartInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CartInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CartInfo) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *CartInfo) GetSizeId() int64 {
	if m != nil {
		return m.SizeId
	}
	return 0
}

func (m *CartInfo) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type ResponseAdd struct {
	CartId               int64    `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseAdd) Reset()         { *m = ResponseAdd{} }
func (m *ResponseAdd) String() string { return proto.CompactTextString(m) }
func (*ResponseAdd) ProtoMessage()    {}
func (*ResponseAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{1}
}

func (m *ResponseAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseAdd.Unmarshal(m, b)
}
func (m *ResponseAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseAdd.Marshal(b, m, deterministic)
}
func (m *ResponseAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseAdd.Merge(m, src)
}
func (m *ResponseAdd) XXX_Size() int {
	return xxx_messageInfo_ResponseAdd.Size(m)
}
func (m *ResponseAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseAdd proto.InternalMessageInfo

func (m *ResponseAdd) GetCartId() int64 {
	if m != nil {
		return m.CartId
	}
	return 0
}

func (m *ResponseAdd) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Clean struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clean) Reset()         { *m = Clean{} }
func (m *Clean) String() string { return proto.CompactTextString(m) }
func (*Clean) ProtoMessage()    {}
func (*Clean) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{2}
}

func (m *Clean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clean.Unmarshal(m, b)
}
func (m *Clean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clean.Marshal(b, m, deterministic)
}
func (m *Clean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clean.Merge(m, src)
}
func (m *Clean) XXX_Size() int {
	return xxx_messageInfo_Clean.Size(m)
}
func (m *Clean) XXX_DiscardUnknown() {
	xxx_messageInfo_Clean.DiscardUnknown(m)
}

var xxx_messageInfo_Clean proto.InternalMessageInfo

func (m *Clean) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Response struct {
	Meg                  string   `protobuf:"bytes,1,opt,name=meg,proto3" json:"meg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMeg() string {
	if m != nil {
		return m.Meg
	}
	return ""
}

type Item struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChangeNum            int64    `protobuf:"varint,2,opt,name=change_num,json=changeNum,proto3" json:"change_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{4}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetChangeNum() int64 {
	if m != nil {
		return m.ChangeNum
	}
	return 0
}

type CartID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartID) Reset()         { *m = CartID{} }
func (m *CartID) String() string { return proto.CompactTextString(m) }
func (*CartID) ProtoMessage()    {}
func (*CartID) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{5}
}

func (m *CartID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartID.Unmarshal(m, b)
}
func (m *CartID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartID.Marshal(b, m, deterministic)
}
func (m *CartID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartID.Merge(m, src)
}
func (m *CartID) XXX_Size() int {
	return xxx_messageInfo_CartID.Size(m)
}
func (m *CartID) XXX_DiscardUnknown() {
	xxx_messageInfo_CartID.DiscardUnknown(m)
}

var xxx_messageInfo_CartID proto.InternalMessageInfo

func (m *CartID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CartFindAll struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartFindAll) Reset()         { *m = CartFindAll{} }
func (m *CartFindAll) String() string { return proto.CompactTextString(m) }
func (*CartFindAll) ProtoMessage()    {}
func (*CartFindAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{6}
}

func (m *CartFindAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartFindAll.Unmarshal(m, b)
}
func (m *CartFindAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartFindAll.Marshal(b, m, deterministic)
}
func (m *CartFindAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartFindAll.Merge(m, src)
}
func (m *CartFindAll) XXX_Size() int {
	return xxx_messageInfo_CartFindAll.Size(m)
}
func (m *CartFindAll) XXX_DiscardUnknown() {
	xxx_messageInfo_CartFindAll.DiscardUnknown(m)
}

var xxx_messageInfo_CartFindAll proto.InternalMessageInfo

func (m *CartFindAll) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CartAll struct {
	CartInfo             []*CartInfo `protobuf:"bytes,1,rep,name=cart_info,json=cartInfo,proto3" json:"cart_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CartAll) Reset()         { *m = CartAll{} }
func (m *CartAll) String() string { return proto.CompactTextString(m) }
func (*CartAll) ProtoMessage()    {}
func (*CartAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d03953aae4c902f, []int{7}
}

func (m *CartAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartAll.Unmarshal(m, b)
}
func (m *CartAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartAll.Marshal(b, m, deterministic)
}
func (m *CartAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartAll.Merge(m, src)
}
func (m *CartAll) XXX_Size() int {
	return xxx_messageInfo_CartAll.Size(m)
}
func (m *CartAll) XXX_DiscardUnknown() {
	xxx_messageInfo_CartAll.DiscardUnknown(m)
}

var xxx_messageInfo_CartAll proto.InternalMessageInfo

func (m *CartAll) GetCartInfo() []*CartInfo {
	if m != nil {
		return m.CartInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*CartInfo)(nil), "cart.CartInfo")
	proto.RegisterType((*ResponseAdd)(nil), "cart.ResponseAdd")
	proto.RegisterType((*Clean)(nil), "cart.Clean")
	proto.RegisterType((*Response)(nil), "cart.Response")
	proto.RegisterType((*Item)(nil), "cart.Item")
	proto.RegisterType((*CartID)(nil), "cart.CartID")
	proto.RegisterType((*CartFindAll)(nil), "cart.CartFindAll")
	proto.RegisterType((*CartAll)(nil), "cart.CartAll")
}

func init() { proto.RegisterFile("cart/proto/cart.proto", fileDescriptor_2d03953aae4c902f) }

var fileDescriptor_2d03953aae4c902f = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x0b, 0xd3, 0x40,
	0x10, 0x6d, 0x3e, 0x9a, 0x36, 0x93, 0x1a, 0xec, 0x82, 0x18, 0x8a, 0x85, 0xb2, 0x88, 0x14, 0x95,
	0x56, 0x2a, 0x8a, 0xe0, 0x29, 0x6d, 0x50, 0x72, 0xf1, 0x90, 0xa3, 0x97, 0x12, 0xb3, 0xdb, 0x18,
	0x48, 0x36, 0x25, 0x1f, 0x07, 0x05, 0xff, 0x82, 0xbf, 0x59, 0x66, 0x92, 0xda, 0x58, 0x2b, 0xde,
	0xde, 0xbc, 0x79, 0x2f, 0xbc, 0x79, 0x1b, 0x78, 0x94, 0xc4, 0x55, 0xb3, 0x3d, 0x57, 0x65, 0x53,
	0x6e, 0x11, 0x6e, 0x08, 0x32, 0x13, 0x31, 0xff, 0x01, 0xd3, 0x43, 0x5c, 0x35, 0xa1, 0x3a, 0x95,
	0xcc, 0x05, 0x3d, 0x13, 0x9e, 0xb6, 0xd2, 0xd6, 0x46, 0xa4, 0x67, 0x82, 0x3d, 0x86, 0x49, 0x5b,
	0xcb, 0xea, 0x98, 0x09, 0x4f, 0x27, 0xd2, 0xc2, 0x31, 0x14, 0x6c, 0x09, 0x70, 0xae, 0x4a, 0xd1,
	0x26, 0x0d, 0xee, 0x0c, 0xda, 0xd9, 0x3d, 0x13, 0x92, 0xaf, 0xce, 0xbe, 0x4b, 0xdc, 0x99, 0x9d,
	0x0f, 0xc7, 0x50, 0xb0, 0x87, 0x60, 0xa8, 0xb6, 0xf0, 0xc6, 0x44, 0x22, 0xe4, 0xef, 0xc0, 0x89,
	0x64, 0x7d, 0x2e, 0x55, 0x2d, 0x7d, 0x41, 0x4e, 0x4c, 0x75, 0xfc, 0x1d, 0xc3, 0xc2, 0xb1, 0x73,
	0x16, 0x75, 0x4a, 0x31, 0xec, 0x08, 0x21, 0x5f, 0xc1, 0xf8, 0x90, 0xcb, 0x58, 0x0d, 0x53, 0x6a,
	0xc3, 0x94, 0xfc, 0x09, 0x4c, 0x2f, 0xdf, 0x26, 0xbf, 0x4c, 0x49, 0x80, 0x7e, 0x99, 0xf2, 0x37,
	0x60, 0x86, 0x8d, 0x2c, 0xfe, 0x3a, 0x7a, 0x09, 0x90, 0x7c, 0x8d, 0x55, 0x2a, 0x8f, 0x18, 0xb5,
	0xbb, 0xdb, 0xee, 0x98, 0x4f, 0x6d, 0xc1, 0x3d, 0xb0, 0xa8, 0xaf, 0xe0, 0xd6, 0xc8, 0x9f, 0x81,
	0x83, 0x9b, 0x0f, 0x99, 0x12, 0x7e, 0x9e, 0xff, 0x3b, 0xd6, 0x5b, 0x98, 0xa0, 0x0e, 0x35, 0x2f,
	0xc0, 0xee, 0xce, 0x55, 0xa7, 0xd2, 0xd3, 0x56, 0xc6, 0xda, 0xd9, 0xb9, 0x1b, 0x7a, 0xa2, 0xcb,
	0x9b, 0x44, 0xd3, 0xa4, 0x47, 0xbb, 0x9f, 0x3a, 0x98, 0x48, 0xb3, 0x0d, 0x4c, 0x7c, 0x21, 0x08,
	0xde, 0xa8, 0x17, 0xf3, 0x6e, 0x1e, 0x54, 0xca, 0x47, 0xec, 0x39, 0xd8, 0xd4, 0x14, 0x39, 0x9c,
	0xde, 0x81, 0xc4, 0xc2, 0xfd, 0x53, 0xce, 0x47, 0xec, 0x29, 0x98, 0xa1, 0x4a, 0x2a, 0x06, 0xdd,
	0x06, 0x1b, 0xba, 0xaf, 0x0a, 0xe4, 0x7f, 0x55, 0xaf, 0xc0, 0x0d, 0x64, 0x2e, 0x1b, 0x89, 0xfb,
	0xfd, 0xb7, 0x30, 0x60, 0xb3, 0x41, 0xdc, 0xe0, 0x8e, 0xe3, 0x25, 0x58, 0x1f, 0x25, 0x35, 0x33,
	0xbf, 0x2a, 0xfb, 0x42, 0x17, 0x0f, 0xae, 0x94, 0x9f, 0xe7, 0x7c, 0xb4, 0x9f, 0x7d, 0x06, 0xfa,
	0x93, 0xdf, 0x23, 0xff, 0xc5, 0x22, 0xfc, 0xfa, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0xa5,
	0x6b, 0xe6, 0xee, 0x02, 0x00, 0x00,
}
