// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/category.proto

package category

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CategoryByLevelResquest struct {
	CategoryLevel        uint32   `protobuf:"varint,1,opt,name=category_level,json=categoryLevel,proto3" json:"category_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryByLevelResquest) Reset()         { *m = CategoryByLevelResquest{} }
func (m *CategoryByLevelResquest) String() string { return proto.CompactTextString(m) }
func (*CategoryByLevelResquest) ProtoMessage()    {}
func (*CategoryByLevelResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{0}
}

func (m *CategoryByLevelResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryByLevelResquest.Unmarshal(m, b)
}
func (m *CategoryByLevelResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryByLevelResquest.Marshal(b, m, deterministic)
}
func (m *CategoryByLevelResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryByLevelResquest.Merge(m, src)
}
func (m *CategoryByLevelResquest) XXX_Size() int {
	return xxx_messageInfo_CategoryByLevelResquest.Size(m)
}
func (m *CategoryByLevelResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryByLevelResquest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryByLevelResquest proto.InternalMessageInfo

func (m *CategoryByLevelResquest) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

type CategoryByIdResquest struct {
	CategoryId           int64    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryByIdResquest) Reset()         { *m = CategoryByIdResquest{} }
func (m *CategoryByIdResquest) String() string { return proto.CompactTextString(m) }
func (*CategoryByIdResquest) ProtoMessage()    {}
func (*CategoryByIdResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{1}
}

func (m *CategoryByIdResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryByIdResquest.Unmarshal(m, b)
}
func (m *CategoryByIdResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryByIdResquest.Marshal(b, m, deterministic)
}
func (m *CategoryByIdResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryByIdResquest.Merge(m, src)
}
func (m *CategoryByIdResquest) XXX_Size() int {
	return xxx_messageInfo_CategoryByIdResquest.Size(m)
}
func (m *CategoryByIdResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryByIdResquest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryByIdResquest proto.InternalMessageInfo

func (m *CategoryByIdResquest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type CategoryByNameResquest struct {
	CategoryName         string   `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryByNameResquest) Reset()         { *m = CategoryByNameResquest{} }
func (m *CategoryByNameResquest) String() string { return proto.CompactTextString(m) }
func (*CategoryByNameResquest) ProtoMessage()    {}
func (*CategoryByNameResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{2}
}

func (m *CategoryByNameResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryByNameResquest.Unmarshal(m, b)
}
func (m *CategoryByNameResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryByNameResquest.Marshal(b, m, deterministic)
}
func (m *CategoryByNameResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryByNameResquest.Merge(m, src)
}
func (m *CategoryByNameResquest) XXX_Size() int {
	return xxx_messageInfo_CategoryByNameResquest.Size(m)
}
func (m *CategoryByNameResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryByNameResquest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryByNameResquest proto.InternalMessageInfo

func (m *CategoryByNameResquest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

type CategoryResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryName         string   `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryLevel        uint32   `protobuf:"varint,3,opt,name=category_level,json=categoryLevel,proto3" json:"category_level,omitempty"`
	CategoryParent       int64    `protobuf:"varint,4,opt,name=category_parent,json=categoryParent,proto3" json:"category_parent,omitempty"`
	CategoryImages       string   `protobuf:"bytes,5,opt,name=category_images,json=categoryImages,proto3" json:"category_images,omitempty"`
	CategoryDescription  string   `protobuf:"bytes,6,opt,name=category_description,json=categoryDescription,proto3" json:"category_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryResponse) Reset()         { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()    {}
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{3}
}

func (m *CategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryResponse.Unmarshal(m, b)
}
func (m *CategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryResponse.Marshal(b, m, deterministic)
}
func (m *CategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryResponse.Merge(m, src)
}
func (m *CategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CategoryResponse.Size(m)
}
func (m *CategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryResponse proto.InternalMessageInfo

func (m *CategoryResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CategoryResponse) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryResponse) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryResponse) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryResponse) GetCategoryImages() string {
	if m != nil {
		return m.CategoryImages
	}
	return ""
}

func (m *CategoryResponse) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

type CategoryRequest struct {
	CategoryName         string   `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryLevel        uint32   `protobuf:"varint,2,opt,name=category_level,json=categoryLevel,proto3" json:"category_level,omitempty"`
	CategoryParent       int64    `protobuf:"varint,3,opt,name=category_parent,json=categoryParent,proto3" json:"category_parent,omitempty"`
	CategoryImages       string   `protobuf:"bytes,4,opt,name=category_images,json=categoryImages,proto3" json:"category_images,omitempty"`
	CategoryDescription  string   `protobuf:"bytes,5,opt,name=category_description,json=categoryDescription,proto3" json:"category_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryRequest) Reset()         { *m = CategoryRequest{} }
func (m *CategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CategoryRequest) ProtoMessage()    {}
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{4}
}

func (m *CategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryRequest.Unmarshal(m, b)
}
func (m *CategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryRequest.Marshal(b, m, deterministic)
}
func (m *CategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryRequest.Merge(m, src)
}
func (m *CategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CategoryRequest.Size(m)
}
func (m *CategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryRequest proto.InternalMessageInfo

func (m *CategoryRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryRequest) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryRequest) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryRequest) GetCategoryImages() string {
	if m != nil {
		return m.CategoryImages
	}
	return ""
}

func (m *CategoryRequest) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

type CreateCategoryResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	CategoryId           int64    `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryResponse) Reset()         { *m = CreateCategoryResponse{} }
func (m *CreateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryResponse) ProtoMessage()    {}
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{5}
}

func (m *CreateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryResponse.Unmarshal(m, b)
}
func (m *CreateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *CreateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryResponse.Merge(m, src)
}
func (m *CreateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryResponse.Size(m)
}
func (m *CreateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryResponse proto.InternalMessageInfo

func (m *CreateCategoryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateCategoryResponse) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type UpdateCategoryResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryResponse) Reset()         { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()    {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{6}
}

func (m *UpdateCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryResponse.Unmarshal(m, b)
}
func (m *UpdateCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryResponse.Merge(m, src)
}
func (m *UpdateCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryResponse.Size(m)
}
func (m *UpdateCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryResponse proto.InternalMessageInfo

func (m *UpdateCategoryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteCategoryResquest struct {
	CategoryId           int64    `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryResquest) Reset()         { *m = DeleteCategoryResquest{} }
func (m *DeleteCategoryResquest) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryResquest) ProtoMessage()    {}
func (*DeleteCategoryResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{7}
}

func (m *DeleteCategoryResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryResquest.Unmarshal(m, b)
}
func (m *DeleteCategoryResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryResquest.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryResquest.Merge(m, src)
}
func (m *DeleteCategoryResquest) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryResquest.Size(m)
}
func (m *DeleteCategoryResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryResquest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryResquest proto.InternalMessageInfo

func (m *DeleteCategoryResquest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type DeleteCategoryResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryResponse) Reset()         { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()    {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{8}
}

func (m *DeleteCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryResponse.Unmarshal(m, b)
}
func (m *DeleteCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryResponse.Merge(m, src)
}
func (m *DeleteCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryResponse.Size(m)
}
func (m *DeleteCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryResponse proto.InternalMessageInfo

func (m *DeleteCategoryResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CategoryByParentResquest struct {
	ParentId             int64    `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryByParentResquest) Reset()         { *m = CategoryByParentResquest{} }
func (m *CategoryByParentResquest) String() string { return proto.CompactTextString(m) }
func (*CategoryByParentResquest) ProtoMessage()    {}
func (*CategoryByParentResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{9}
}

func (m *CategoryByParentResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryByParentResquest.Unmarshal(m, b)
}
func (m *CategoryByParentResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryByParentResquest.Marshal(b, m, deterministic)
}
func (m *CategoryByParentResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryByParentResquest.Merge(m, src)
}
func (m *CategoryByParentResquest) XXX_Size() int {
	return xxx_messageInfo_CategoryByParentResquest.Size(m)
}
func (m *CategoryByParentResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryByParentResquest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryByParentResquest proto.InternalMessageInfo

func (m *CategoryByParentResquest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type FindAllResquest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllResquest) Reset()         { *m = FindAllResquest{} }
func (m *FindAllResquest) String() string { return proto.CompactTextString(m) }
func (*FindAllResquest) ProtoMessage()    {}
func (*FindAllResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{10}
}

func (m *FindAllResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllResquest.Unmarshal(m, b)
}
func (m *FindAllResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllResquest.Marshal(b, m, deterministic)
}
func (m *FindAllResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllResquest.Merge(m, src)
}
func (m *FindAllResquest) XXX_Size() int {
	return xxx_messageInfo_FindAllResquest.Size(m)
}
func (m *FindAllResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllResquest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllResquest proto.InternalMessageInfo

type FindAllResponse struct {
	All                  []*CategoryResponse `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FindAllResponse) Reset()         { *m = FindAllResponse{} }
func (m *FindAllResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllResponse) ProtoMessage()    {}
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bfb247fa9b1cc73, []int{11}
}

func (m *FindAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllResponse.Unmarshal(m, b)
}
func (m *FindAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllResponse.Marshal(b, m, deterministic)
}
func (m *FindAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllResponse.Merge(m, src)
}
func (m *FindAllResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllResponse.Size(m)
}
func (m *FindAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllResponse proto.InternalMessageInfo

func (m *FindAllResponse) GetAll() []*CategoryResponse {
	if m != nil {
		return m.All
	}
	return nil
}

func init() {
	proto.RegisterType((*CategoryByLevelResquest)(nil), "category.CategoryByLevelResquest")
	proto.RegisterType((*CategoryByIdResquest)(nil), "category.CategoryByIdResquest")
	proto.RegisterType((*CategoryByNameResquest)(nil), "category.CategoryByNameResquest")
	proto.RegisterType((*CategoryResponse)(nil), "category.CategoryResponse")
	proto.RegisterType((*CategoryRequest)(nil), "category.CategoryRequest")
	proto.RegisterType((*CreateCategoryResponse)(nil), "category.CreateCategoryResponse")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "category.UpdateCategoryResponse")
	proto.RegisterType((*DeleteCategoryResquest)(nil), "category.DeleteCategoryResquest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "category.DeleteCategoryResponse")
	proto.RegisterType((*CategoryByParentResquest)(nil), "category.CategoryByParentResquest")
	proto.RegisterType((*FindAllResquest)(nil), "category.FindAllResquest")
	proto.RegisterType((*FindAllResponse)(nil), "category.FindAllResponse")
}

func init() { proto.RegisterFile("proto/category.proto", fileDescriptor_1bfb247fa9b1cc73) }

var fileDescriptor_1bfb247fa9b1cc73 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xe1, 0x6a, 0xd4, 0x40,
	0x10, 0xbe, 0x4b, 0x7a, 0xe5, 0x3a, 0xb5, 0xb9, 0x73, 0x7b, 0x9c, 0x31, 0x82, 0xd6, 0x15, 0xb1,
	0x14, 0xa9, 0x58, 0x7f, 0x14, 0x11, 0x51, 0xdb, 0x22, 0x04, 0x45, 0x4b, 0xb0, 0x0a, 0xfe, 0x29,
	0xb1, 0x3b, 0x1c, 0x81, 0x5c, 0x12, 0x93, 0x28, 0xf4, 0x89, 0x7c, 0x2f, 0x5f, 0xc1, 0x17, 0x90,
	0x6c, 0x6e, 0x37, 0xd9, 0x64, 0x2f, 0xc6, 0x7f, 0xd9, 0x99, 0xef, 0xfb, 0xe6, 0x66, 0xf6, 0x9b,
	0x3d, 0x98, 0x25, 0x69, 0x9c, 0xc7, 0x4f, 0xae, 0xfc, 0x1c, 0x17, 0x71, 0x7a, 0x7d, 0xc8, 0x8f,
	0x64, 0x2c, 0xce, 0xf4, 0x35, 0xdc, 0x3a, 0x5d, 0x7d, 0x9f, 0x5c, 0xbf, 0xc7, 0x9f, 0x18, 0x7a,
	0x98, 0x7d, 0xff, 0x81, 0x59, 0x4e, 0x1e, 0x82, 0x25, 0x60, 0x97, 0x61, 0x91, 0xb1, 0x87, 0x7b,
	0xc3, 0xfd, 0x1d, 0x6f, 0x47, 0x44, 0x39, 0x9c, 0x1e, 0xc3, 0xac, 0x52, 0x70, 0x99, 0xa4, 0xdf,
	0x83, 0x6d, 0x49, 0x0f, 0x18, 0xe7, 0x9a, 0x1e, 0x88, 0x90, 0xcb, 0xe8, 0x4b, 0x98, 0x57, 0xc4,
	0x0f, 0xfe, 0x12, 0x25, 0xf5, 0x01, 0xc8, 0x1a, 0x97, 0x91, 0xbf, 0x44, 0x4e, 0xde, 0xf2, 0x6e,
	0x88, 0x60, 0x01, 0xa6, 0x7f, 0x86, 0x30, 0x15, 0x7c, 0x0f, 0xb3, 0x24, 0x8e, 0x32, 0x24, 0x16,
	0x18, 0xb2, 0x96, 0x11, 0xb0, 0xb6, 0x92, 0xd1, 0x56, 0xd2, 0x34, 0x6a, 0x6a, 0x1a, 0x25, 0x8f,
	0x60, 0x22, 0x61, 0x89, 0x9f, 0x62, 0x94, 0xdb, 0x1b, 0xbc, 0x90, 0x64, 0x9f, 0xf3, 0xa8, 0x02,
	0x0c, 0x96, 0xfe, 0x02, 0x33, 0x7b, 0xc4, 0xcb, 0x4a, 0xa0, 0xcb, 0xa3, 0xe4, 0x29, 0xcc, 0x24,
	0x90, 0x61, 0x76, 0x95, 0x06, 0x49, 0x1e, 0xc4, 0x91, 0xbd, 0xc9, 0xd1, 0xbb, 0x22, 0x77, 0x56,
	0xa5, 0xe8, 0xef, 0x21, 0x4c, 0xaa, 0xae, 0xfb, 0x8f, 0x4b, 0xd3, 0xa4, 0xd1, 0xb3, 0x49, 0xb3,
	0x6f, 0x93, 0x1b, 0xff, 0xd5, 0xe4, 0x68, 0x7d, 0x93, 0xef, 0x60, 0x7e, 0x9a, 0xa2, 0x9f, 0x63,
	0xeb, 0x7e, 0xa7, 0x60, 0x2e, 0xb3, 0xc5, 0xaa, 0xc1, 0xe2, 0xb3, 0x69, 0x33, 0xa3, 0x65, 0xb3,
	0x03, 0x98, 0x5f, 0x24, 0xac, 0x97, 0x18, 0x7d, 0x0e, 0xf3, 0x33, 0x0c, 0x51, 0xc1, 0xf6, 0x74,
	0xf3, 0x81, 0x86, 0xba, 0xae, 0xcc, 0x31, 0xd8, 0x95, 0xf3, 0xcb, 0x79, 0xca, 0x42, 0x77, 0x60,
	0xab, 0x9c, 0x7b, 0x55, 0x66, 0x5c, 0x06, 0x5c, 0x46, 0x6f, 0xc2, 0xe4, 0x6d, 0x10, 0xb1, 0x37,
	0xa1, 0xdc, 0x52, 0xfa, 0xaa, 0x1e, 0x2a, 0x0b, 0x3e, 0x06, 0xd3, 0x0f, 0x8b, 0x6d, 0x35, 0xf7,
	0xb7, 0x8f, 0x9c, 0x43, 0xb9, 0xfb, 0xcd, 0x5f, 0xe6, 0x15, 0xb0, 0xa3, 0x5f, 0x23, 0x18, 0x8b,
	0x0c, 0xf9, 0x08, 0x96, 0x3a, 0x79, 0x72, 0x5b, 0xc7, 0xe7, 0xa5, 0x9d, 0xbd, 0x5a, 0x4a, 0x7b,
	0x5d, 0x74, 0x50, 0x08, 0xaa, 0xd3, 0xef, 0x29, 0xa8, 0xbf, 0x32, 0x3a, 0x20, 0x9f, 0xc1, 0x52,
	0xe7, 0x4c, 0x6a, 0x2c, 0xfd, 0xe5, 0x39, 0x5d, 0x08, 0xa1, 0xfb, 0x09, 0x48, 0x31, 0x47, 0xf5,
	0x45, 0xaa, 0x6b, 0xeb, 0xdf, 0x2a, 0xa7, 0x63, 0xbe, 0x74, 0x40, 0xce, 0x61, 0xaa, 0xaa, 0xba,
	0x8c, 0xdc, 0xd5, 0x69, 0x56, 0x0f, 0xe7, 0x3f, 0x14, 0x2f, 0x60, 0x57, 0x55, 0x2c, 0xf7, 0xf6,
	0xbe, 0x4e, 0x54, 0x79, 0xcf, 0x9d, 0xda, 0xe0, 0x1b, 0x8e, 0xa1, 0x03, 0xf2, 0x05, 0x66, 0xaa,
	0xec, 0x6a, 0xcd, 0xa9, 0x4e, 0x57, 0xb5, 0x6c, 0xb7, 0xb0, 0x2b, 0xfd, 0xa9, 0x73, 0x40, 0xc3,
	0xcd, 0x9d, 0x52, 0x27, 0xd3, 0xaf, 0x16, 0xff, 0xfb, 0x7a, 0x21, 0x30, 0xdf, 0x36, 0xf9, 0xf9,
	0xd9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xb2, 0x98, 0x40, 0xe6, 0x06, 0x00, 0x00,
}
