// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResuqestRegister struct {
	Avatar               string   `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	RePassword           string   `protobuf:"bytes,5,opt,name=re_password,json=rePassword,proto3" json:"re_password,omitempty"`
	Sex                  int32    `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Tel                  string   `protobuf:"bytes,7,opt,name=tel,proto3" json:"tel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResuqestRegister) Reset()         { *m = ResuqestRegister{} }
func (m *ResuqestRegister) String() string { return proto.CompactTextString(m) }
func (*ResuqestRegister) ProtoMessage()    {}
func (*ResuqestRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *ResuqestRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResuqestRegister.Unmarshal(m, b)
}
func (m *ResuqestRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResuqestRegister.Marshal(b, m, deterministic)
}
func (m *ResuqestRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResuqestRegister.Merge(m, src)
}
func (m *ResuqestRegister) XXX_Size() int {
	return xxx_messageInfo_ResuqestRegister.Size(m)
}
func (m *ResuqestRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ResuqestRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ResuqestRegister proto.InternalMessageInfo

func (m *ResuqestRegister) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ResuqestRegister) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ResuqestRegister) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResuqestRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResuqestRegister) GetRePassword() string {
	if m != nil {
		return m.RePassword
	}
	return ""
}

func (m *ResuqestRegister) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *ResuqestRegister) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

type ResponseRegister struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseRegister) Reset()         { *m = ResponseRegister{} }
func (m *ResponseRegister) String() string { return proto.CompactTextString(m) }
func (*ResponseRegister) ProtoMessage()    {}
func (*ResponseRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *ResponseRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseRegister.Unmarshal(m, b)
}
func (m *ResponseRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseRegister.Marshal(b, m, deterministic)
}
func (m *ResponseRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseRegister.Merge(m, src)
}
func (m *ResponseRegister) XXX_Size() int {
	return xxx_messageInfo_ResponseRegister.Size(m)
}
func (m *ResponseRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseRegister proto.InternalMessageInfo

func (m *ResponseRegister) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseRegister) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseRegister) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type ResquestLogin struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResquestLogin) Reset()         { *m = ResquestLogin{} }
func (m *ResquestLogin) String() string { return proto.CompactTextString(m) }
func (*ResquestLogin) ProtoMessage()    {}
func (*ResquestLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *ResquestLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResquestLogin.Unmarshal(m, b)
}
func (m *ResquestLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResquestLogin.Marshal(b, m, deterministic)
}
func (m *ResquestLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResquestLogin.Merge(m, src)
}
func (m *ResquestLogin) XXX_Size() int {
	return xxx_messageInfo_ResquestLogin.Size(m)
}
func (m *ResquestLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResquestLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResquestLogin proto.InternalMessageInfo

func (m *ResquestLogin) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ResquestLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseLogin struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseLogin) Reset()         { *m = ResponseLogin{} }
func (m *ResponseLogin) String() string { return proto.CompactTextString(m) }
func (*ResponseLogin) ProtoMessage()    {}
func (*ResponseLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{3}
}

func (m *ResponseLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLogin.Unmarshal(m, b)
}
func (m *ResponseLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLogin.Marshal(b, m, deterministic)
}
func (m *ResponseLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLogin.Merge(m, src)
}
func (m *ResponseLogin) XXX_Size() int {
	return xxx_messageInfo_ResponseLogin.Size(m)
}
func (m *ResponseLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLogin proto.InternalMessageInfo

func (m *ResponseLogin) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseLogin) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseLogin) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type ResquestUserInfo struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResquestUserInfo) Reset()         { *m = ResquestUserInfo{} }
func (m *ResquestUserInfo) String() string { return proto.CompactTextString(m) }
func (*ResquestUserInfo) ProtoMessage()    {}
func (*ResquestUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{4}
}

func (m *ResquestUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResquestUserInfo.Unmarshal(m, b)
}
func (m *ResquestUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResquestUserInfo.Marshal(b, m, deterministic)
}
func (m *ResquestUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResquestUserInfo.Merge(m, src)
}
func (m *ResquestUserInfo) XXX_Size() int {
	return xxx_messageInfo_ResquestUserInfo.Size(m)
}
func (m *ResquestUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResquestUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResquestUserInfo proto.InternalMessageInfo

func (m *ResquestUserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

type ResponseUserInfo struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseUserInfo) Reset()         { *m = ResponseUserInfo{} }
func (m *ResponseUserInfo) String() string { return proto.CompactTextString(m) }
func (*ResponseUserInfo) ProtoMessage()    {}
func (*ResponseUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{5}
}

func (m *ResponseUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseUserInfo.Unmarshal(m, b)
}
func (m *ResponseUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseUserInfo.Marshal(b, m, deterministic)
}
func (m *ResponseUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseUserInfo.Merge(m, src)
}
func (m *ResponseUserInfo) XXX_Size() int {
	return xxx_messageInfo_ResponseUserInfo.Size(m)
}
func (m *ResponseUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseUserInfo proto.InternalMessageInfo

func (m *ResponseUserInfo) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseUserInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseUserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func init() {
	proto.RegisterType((*ResuqestRegister)(nil), "user.ResuqestRegister")
	proto.RegisterType((*ResponseRegister)(nil), "user.ResponseRegister")
	proto.RegisterType((*ResquestLogin)(nil), "user.ResquestLogin")
	proto.RegisterType((*ResponseLogin)(nil), "user.ResponseLogin")
	proto.RegisterType((*ResquestUserInfo)(nil), "user.ResquestUserInfo")
	proto.RegisterType((*ResponseUserInfo)(nil), "user.ResponseUserInfo")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0xd0, 0x22, 0x0c, 0x9a, 0x90, 0x25, 0x21, 0x0d, 0x1e, 0x24, 0x7b, 0xe2, 0x04, 0x89,
	0x1c, 0x35, 0x31, 0xf1, 0xa2, 0x26, 0xc6, 0x98, 0x4d, 0xb8, 0x78, 0x21, 0x15, 0x46, 0x42, 0x94,
	0x2e, 0xec, 0x2c, 0xea, 0xb7, 0x19, 0x3f, 0xce, 0xec, 0x40, 0x5b, 0xb6, 0x07, 0x2f, 0x7a, 0x7b,
	0xfb, 0xe6, 0xcd, 0xf0, 0xde, 0x30, 0x85, 0xf6, 0xda, 0x68, 0xab, 0x47, 0x5b, 0x42, 0x33, 0x64,
	0x28, 0x42, 0x87, 0xe5, 0x77, 0x00, 0x6d, 0x85, 0xb4, 0xdd, 0x20, 0x59, 0x85, 0x8b, 0x25, 0x59,
	0x34, 0xa2, 0x0b, 0xf5, 0xe4, 0x3d, 0xb1, 0x89, 0x89, 0x83, 0x7e, 0x30, 0x68, 0xaa, 0xfd, 0x4b,
	0x9c, 0x42, 0x33, 0x5d, 0xce, 0x5e, 0xa7, 0x69, 0xb2, 0xc2, 0xb8, 0xca, 0xa5, 0x86, 0x23, 0x1e,
	0x92, 0x15, 0x0a, 0x01, 0x21, 0xf3, 0x35, 0xe6, 0x19, 0x8b, 0x1e, 0x34, 0xd6, 0x09, 0xd1, 0x87,
	0x36, 0xf3, 0x38, 0xdc, 0xe9, 0xb3, 0xb7, 0x38, 0x83, 0x96, 0xc1, 0x69, 0x5e, 0x8e, 0xb8, 0x0c,
	0x06, 0x1f, 0x33, 0x41, 0x1b, 0x6a, 0x84, 0x9f, 0x71, 0xbd, 0x1f, 0x0c, 0x22, 0xe5, 0xa0, 0x63,
	0x2c, 0xbe, 0xc5, 0x47, 0x2c, 0x75, 0x50, 0x4e, 0xd8, 0xfd, 0x5a, 0xa7, 0x84, 0xb9, 0x7b, 0x01,
	0xe1, 0x4c, 0xcf, 0x91, 0xbd, 0x47, 0x8a, 0xb1, 0xeb, 0x5c, 0xd1, 0x62, 0xef, 0xd9, 0x41, 0x3f,
	0x4b, 0xcd, 0xcf, 0x22, 0x6f, 0xe1, 0x44, 0x21, 0x6d, 0xb6, 0x48, 0xf6, 0x5e, 0x2f, 0x96, 0xa9,
	0xaf, 0x0e, 0x4a, 0xc9, 0x0f, 0x53, 0x56, 0xfd, 0x94, 0x52, 0xf1, 0x24, 0x36, 0xb8, 0x9b, 0xf4,
	0x0f, 0xee, 0x46, 0x1c, 0x9a, 0xdd, 0x4d, 0x08, 0xcd, 0x5d, 0xfa, 0xa2, 0x7f, 0x35, 0x78, 0xb8,
	0xa5, 0xbc, 0xe1, 0xef, 0x3e, 0xce, 0xbf, 0x02, 0x08, 0xdd, 0x3c, 0x71, 0x09, 0x8d, 0xe2, 0x76,
	0x86, 0x7c, 0x63, 0xe5, 0x9b, 0xea, 0x15, 0xbc, 0xf7, 0x6f, 0xc9, 0x8a, 0x18, 0x43, 0xb4, 0x5b,
	0x4d, 0x27, 0x97, 0x14, 0x9b, 0xef, 0x75, 0xfc, 0x3e, 0x26, 0x65, 0x45, 0x5c, 0x41, 0xeb, 0x06,
	0x8b, 0xf8, 0x5d, 0xbf, 0x35, 0xe3, 0xcb, 0xbf, 0x9a, 0xf1, 0xb2, 0x72, 0x7d, 0xfc, 0x04, 0xfc,
	0x1d, 0x5c, 0x38, 0xc1, 0x73, 0x9d, 0xf1, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0x95, 0x23, 0xed,
	0xb6, 0x27, 0x03, 0x00, 0x00,
}
